name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      - name: Install npm dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint:js
      - name: Run remark-lint
        run: yarn lint:md
      - name: Run unit tests
        run: yarn cover
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          HOMITALDB_CONNECTIONSTRING: ${{ secrets.HOMITALDB_CONNECTIONSTRING }}
          NOREPLY_EMAIL_HOST: ${{ secrets.NOREPLY_EMAIL_HOST }}
          NOREPLY_EMAIL_PORT: ${{ secrets.NOREPLY_EMAIL_PORT }}
          NOREPLY_EMAIL_ADDR: ${{ secrets.NOREPLY_EMAIL_ADDR }}
          NOREPLY_EMAIL_PASS: ${{ secrets.NOREPLY_EMAIL_PASS }}
      - name: Upload to Codecov
        run: |
          yarn codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
